### ISSUE TITLE
TypeError: remixd.Router is not a constructor

### ISSUE THREAD

**Issue by 15895880466** [ethereum/remix-project#1024]
can not install remix by npm . i run "npm install -g remix-ide" successfully,but when i run "remix-ide",it doesnt work. here is the error log:
TypeError: remixd.Router is not a constructor
    at Object.<anonymous> (/usr/local/lib/node_modules/remix-ide/bin/remix-ide:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by doncesarts** [comment]
If you modify the binary file  from `remixd.Router` to  `remixd.Websocket` it will run as expected.  

```
var router = new remixd.Websocket(65520, remixd.services.sharedFolder, { remixIdeUrl: 'http://localhost:8080' }, (webSocket) => {
  remixd.services.sharedFolder.setWebSocket(webSocket)
  remixd.services.sharedFolder.setupNotifications(folder)
  remixd.services.sharedFolder.sharedFolder(folder, false)
})
```
