### ISSUE TITLE
JavaScript error on page load

### ISSUE THREAD

**Issue by mrosendin** [ethereum/remix-project#1074]
I went to [https://remix.ethereum.org/](https://remix.ethereum.org/) and I'm getting this error. Can't even create a new file.

Using Chrome

```
n {syscall: "", errno: 2, code: "ENOENT", path: "/.workspaces", stack: "Error↵    at new n (https://remix.ethereum.org/ass….ethereum.org/assets/js/browserfs.min.js:7:78203)", …}
code: "ENOENT"
errno: 2
message: "Error: ENOENT: No such file or directory., '/.workspaces'"
path: "/.workspaces"
stack: "Error↵    at new n (https://remix.ethereum.org/assets/js/browserfs.min.js:7:62518)↵    at Function.n.FileError (https://remix.ethereum.org/assets/js/browserfs.min.js:7:62983)↵    at Function.n.ENOENT (https://remix.ethereum.org/assets/js/browserfs.min.js:7:63034)↵    at i (https://remix.ethereum.org/assets/js/browserfs.min.js:7:122604)↵    at e.n._findINode (https://remix.ethereum.org/assets/js/browserfs.min.js:7:122654)↵    at e.n.findINode (https://remix.ethereum.org/assets/js/browserfs.min.js:7:122826)↵    at e.n.readdirSync (https://remix.ethereum.org/assets/js/browserfs.min.js:7:121962)↵    at e.readdir (https://remix.ethereum.org/assets/js/browserfs.min.js:7:90284)↵    at Te.readdir (https://remix.ethereum.org/assets/js/browserfs.min.js:7:74713)↵    at Object.Le.<computed>.xe.<computed> [as readdir] (https://remix.ethereum.org/assets/js/browserfs.min.js:7:78203)"
syscall: ""
__proto__: Error
```

```
Uncaught (in promise) Error: Error: Error: undefined No workspace has been opened.
    at FileManager._callee10$ (main.js:2881)
    at tryCatch (polyfills.js:983)
    at Generator.invoke [as _invoke] (polyfills.js:1001)
    at Generator.prototype.<computed> [as throw] (polyfills.js:988)
    at asyncGeneratorStep (main.js:2851)
    at _throw (main.js:2852)
```

**Comment by petscheit** [comment]
+1

**Comment by MartinMinkov** [comment]
+1

**Comment by Nokhal** [comment]
#1089 related ?
