### ISSUE TITLE
Cannot read/write to  path outside shared folder.

### ISSUE THREAD

**Issue by kevupton** [ethereum/remix-project#1307]
Using `../` in import breaks the localhost connection building.

Example:

```sol
import "../interfaces/Context.sol";
```

```
Error: Cannot read/write to path outside shared folder.
    at Object.absolutePath (------\node_modules\@remix-project\remixd\utils.js:20:15)
    at RemixdClient.exists (------\node_modules\@remix-project\remixd\services\remixdClient.js:75:32)
    at Object.<anonymous> (------\node_modules\@remix-project\remixd\node_modules\@remixproject\plugin\lib\connector.js:67:56)
    at Generator.next (<anonymous>)
    at ------\node_modules\@remix-project\remixd\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (------\node_modules\@remix-project\remixd\node_modules\tslib\tslib.js:110:16)
    at ------\node_modules\@remix-project\remixd\node_modules\@remixproject\plugin\lib\connector.js:30:86
    at WebSocket.<anonymous> (------\node_modules\@remix-project\remixd\node_modules\@remixproject\plugin-ws\lib\ws.js:35:17)
    at WebSocket.emit (events.js:315:20)
```

**Comment by Aniket-Engg** [comment]
@kevupton Please make sure the file you are trying to access is inside the shared folder

**Comment by kevupton** [comment]
@Aniket-Engg thanks for getting back to me, the path was inside the share folder. 

The structure of the project looked like this:

- contracts/abstracts/SomeAbstract.sol <-- here we have the `import "../interfaces/Context.sol";`
- contracts/interfaces/Context.sol
- contracts/Main.sol <-- here we import SomeAbstract

The command is run from `.` directory where `contracts` folder is. So they are all inside the shared location. It works when you have `./` but `../` for an import breaks it. I had a look at the code. The `../` import was sending it outside the main shared folder, instead of just outside the `abstracts` folder.

**Comment by kevupton** [comment]
just as a note from `SomeAbstract.sol` I have to manually put `contracts/interfaces/Context.sol` is the only way to reach it. Which does not seem correct.
