### ISSUE TITLE
Debugger not working on Rinkeby

### ISSUE THREAD

**Issue by merlincdj** [ethereum/remix-project#1841]
When I debug on JavaScript VM, the debugger work as usual.
When I Using Injected Web3 connect to Rinkeby, the debugger not working.
I'm playing the ethernaut with Rinkeby, some levels need to debug. Thank you if you could help.
![image](https://user-images.githubusercontent.com/39942523/146221315-0d37aa33-3cfa-423e-a038-1be736eec651.png)

**Comment by merlincdj** [comment]
same Error on Ropsten

**Comment by skimaharvey** [comment]
Did you find any solution to this pb?

**Comment by kylebakerio** [comment]
I also see an error when attempting to debug a transaction on rinkeby. Button shows no response, but I see this in the terminal:

```
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (vendors~app.js:159647:16)
    at XMLHttpRequest.request.onreadystatechange (vendors~app.js:172726:32)
startDebugging @ app.js:2145
setTimeout (async)
_fireError @ vendors~app.js:11571
sendTxCallback @ vendors~app.js:42002
(anonymous) @ vendors~app.js:159583
request.onreadystatechange @ vendors~app.js:172729
```

The problem seem to uniqudly be for me when I am attempting a transaction that lacks solidity source, as far as I can tell. Otherwise, this seems to work fine. And as far as I can tell, no other tool exists for me to easily debug opcode flow of transactions that are not verified.

I was actually working on this same ethernauts problem. I ended up just working with the raw bytecode and annotating it by hand, which was kind of a pain (but also kind of fun if I'm being honest), but I still would really like for this tool to work.

**Comment by LianaHus** [comment]
we will fix this ASAP. thanks for report

**Comment by yangchenyun** [comment]
Also encountered this issue, it seems the server doesn't respond properly. 
How could I help? It is possible to change the RPC endpoint to debug?

```
❯ curl 'https://remix-rinkeby.ethdevops.io/' \
        -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"' \
        -H 'Referer: https://remix.ethereum.org/' \
        -H 'DNT: 1' \
        -H 'sec-ch-ua-mobile: ?0' \
        -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36' \
        -H 'sec-ch-ua-platform: "macOS"' \
        -H 'Content-Type: application/json' \
        --data-raw '{"jsonrpc":"2.0","id":2255,"method":"net_version","params":[]}' \
        --compressed
```
