### ISSUE TITLE
"Error: Error from IDE : data out-of-bounds" when contract assertion fails.

### ISSUE THREAD

**Issue by musicslayer** [ethereum/remix-project#3024]
Contract: Foo.sol
Compiler: 0.8.17+commit.8df45f5f

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.12 <0.9.0;
contract Foo {
    function foo() public {
        assert(false);
    }
}
```

Run the following JavaScript file (runFoo.js):

```
const { ethers } = require("hardhat");

function handleError(err) {
    console.log('ERROR:');
    console.log(JSON.stringify(err, Object.getOwnPropertyNames(err), 4));
}

async function async_runFoo() {
    const fooFactory = await ethers.getContractFactory("Foo");
    const fooContract = await fooFactory.deploy();
    await fooContract.deployed();

    const call_foo = await fooContract.foo();
    await call_foo.wait();
}

async_runFoo().catch(handleError);
```

In the console you will see:

```
null
ERROR:
{
    "stack": "Error: Error from IDE : data out-of-bounds (length=31, offset=32, code=BUFFER_OVERRUN, version=abi/5.5.0)\n    at a.<anonymous> (https://yann300.github.io/remix-script-runner/script-runner.js:2:145540)\n    at Object.l (https://yann300.github.io/remix-script-runner/script-runner.js:2:151969)\n    at a.emit (https://yann300.github.io/remix-script-runner/script-runner.js:2:153682)\n    at Object.<anonymous> (https://yann300.github.io/remix-script-runner/script-runner.js:2:147683)\n    at Generator.next (<anonymous>)\n    at https://yann300.github.io/remix-script-runner/script-runner.js:2:1253287\n    at new Promise (<anonymous>)\n    at Module.l (https://yann300.github.io/remix-script-runner/script-runner.js:2:1253032)\n    at https://yann300.github.io/remix-script-runner/script-runner.js:2:147281\n    at o.<anonymous> (https://yann300.github.io/remix-script-runner/script-runner.js:2:137997)",
    "message": "Error from IDE : data out-of-bounds (length=31, offset=32, code=BUFFER_OVERRUN, version=abi/5.5.0)"
}
```

I would have expected to see something like this instead:

```
ERROR:
{
    "stack": "Error: call revert exception; VM Exception while processing transaction: reverted with panic code 1 [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"foo()\", data=\"0x4e487b710000000000000000000000000000000000000000000000000000000000000001\", errorArgs=[{\"type\":\"BigNumber\",\"hex\":\"0x01\"}], errorName=\"Panic\", errorSignature=\"Panic(uint256)\", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at d.makeError (https://yann300.github.io/remix-script-runner/script-runner.js:2:75814)\n    at d.throwError (https://yann300.github.io/remix-script-runner/script-runner.js:2:75934)\n    at ht.decodeFunctionResult (https://yann300.github.io/remix-script-runner/script-runner.js:2:555338)\n    at Vr.<anonymous> (https://yann300.github.io/remix-script-runner/script-runner.js:2:605870)\n    at Generator.next (<anonymous>)\n    at o (https://yann300.github.io/remix-script-runner/script-runner.js:2:601565)",
    "message": "call revert exception; VM Exception while processing transaction: reverted with panic code 1 [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"foo()\", data=\"0x4e487b710000000000000000000000000000000000000000000000000000000000000001\", errorArgs=[{\"type\":\"BigNumber\",\"hex\":\"0x01\"}], errorName=\"Panic\", errorSignature=\"Panic(uint256)\", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)",
    "reason": null,
    "code": "CALL_EXCEPTION",
    "method": "foo()",
    "data": "0x4e487b710000000000000000000000000000000000000000000000000000000000000001",
    "errorArgs": [
        {}
    ],
    "errorName": "Panic",
    "errorSignature": "Panic(uint256)",
    "address": "0x56a2777e796eF23399e9E1d791E1A0410a75E31b",
    "args": [],
    "transaction": {
        "data": "0xc2985578"
    }
}
```

**Comment by nishuzumi** [comment]
I have found the cause of the problem and I will submit a pr

**Comment by LashmanS** [comment]
> I have found the cause of the problem and I will submit a pr

I'm facing the same issue

**Comment by buley** [comment]
I am encountering this error when using the `1_Storage.sol` example contract on Remix.

```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.2 <0.9.0;

/**
 * @title Storage
 * @dev Store & retrieve value in a variable
 * @custom:dev-run-script ./scripts/deploy_with_ethers.ts
 */
contract Storage {

    uint256 number;

    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retrieve() public view returns (uint256){
        return number;
    }
}
```

**Comment by eliphang** [comment]
> I have found the cause of the problem and I will submit a pr

Would you like to submit the PR or tell us where the problem is?

Still facing this issue when testing custom errors with no arguments. If the custom errors have arguments, I don't get the error.
