### ISSUE TITLE
Failing to generate artifacts after compiling

### ISSUE THREAD

**Issue by tklindt** [ethereum/remix-project#3138]
This issue started yesterday (16-11-2022) at about 23:00 UTC. When compiling a contract the artifacts are no longer being generated. In the console there is the following error:
```
Uncaught (in promise) SyntaxError: Unexpected token '<', "<binary co"... is not valid JSON
    at JSON.parse (<anonymous>)
    at CompilerMetadata.removeStoredBuildInfo (app.0.29.0-dev.1668527239915.js:32974:28)
    at async CompilerMetadata.setBuildInfo (app.0.29.0-dev.1668527239915.js:32998:7)
    at async Object.[solidity] compilationFinished (app.0.29.0-dev.1668527239915.js:32949:7)
```
This issue is happening across multiple compiler versions, contracts, devices, OS, etc.

**Comment by Aniket-Engg** [comment]
hello @tklindt , artifacts generation works fine for me. Can you please ensure that artifact files are not manually updated.
