### ISSUE TITLE
Issue in opening relative files from file

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#3256]
If I CTRL+click on the path `import "../contracts/MyToken.sol";` from `tests` folder, it doesn't open the file and shows this in browser console:
```
Error: Error: Cannot read/write to path outside workspace
    at FileManager._callee4$ (app.0.29.0.1671180951970.js:2501:772)
    at tryCatch (main.0.29.0.1671180951970.js:4696:81)
    at Generator.invoke [as _invoke] (main.0.29.0.1671180951970.js:4714:36)
    at Generator.throw (main.0.29.0.1671180951970.js:4701:471)
    at asyncGeneratorStep (main.0.29.0.1671180951970.js:2476:260)
    at _throw (main.0.29.0.1671180951970.js:2479:22)
```

**Comment by joeizang** [comment]
Not exactly what I am experiencing but there might be a bug here.
