### ISSUE TITLE
timeout when calling udapp API from a plugin and working on a public testnet 

### ISSUE THREAD

**Issue by aelmanaa** [ethereum/remix-project#3333]
Hi,

When I run a transaction using a plugin. E.g.,

```javascript
    const transaction: RemixTx = {
      from: signerAccount,
      to: this.contractAddress,
      data: dataTrans,
      gasLimit: "500000",
      value: "0x00",
      useCall: false,
    };
const txReceipt = await this.call("udapp", "sendTransaction", transaction);
```

Error : ` _this15.web3(...).eth.getExecutionResultFromSimulator`

I noticed that this error occurs only when I'm working on a public testnet (so the transaction can takes a few seconds to be included in a block):

```
client.js:84 Uncaught (in promise) Error: Error from IDE : [TIMEOUT] Timeout for call sendTransaction from XX
    at EventEmitter.<anonymous> (client.js:84:1)
    at Object.onceWrapper (events.js:199:1)
    at EventEmitter.emit (events.js:127:1)
    at Object.<anonymous> (connector.js:79:1)
    at Generator.next (<anonymous>)
    at tslib.es6.js:149:1
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js:131:1)
    at connector.js:44:1
    at WebviewConnector.<anonymous> (connector.js:74:1)
```

**Comment by yann300** [comment]
thanks for creating the issue, that is fixed and soon deployed to remix-alpha.ethereum.org (it will land in live next week)
