### ISSUE TITLE
Switching to other providers without unlocking Metamask. 

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3416]
We see an error in the browser terminal but nothing in UI.
There should be clear feedback on all user actions, including (especially) in case of errors.

**Comment by LianaHus** [comment]
```
:1 Uncaught (in promise) Error: Please make sure the injected provider is unlocked (e.g Metamask).
    at BasicInjectedProvider._callee$ (824.0.31.0-dev.1677054177163.js:1:300766)
    at tryCatch (polyfills.0.31.0-dev.1677054177163.js:1:312146)
    at Generator.invoke [as _invoke] (polyfills.0.31.0-dev.1677054177163.js:1:316097)
    at Generator.next (polyfills.0.31.0-dev.1677054177163.js:1:313285)
    at asyncGeneratorStep (main.0.31.0-dev.1677054177163.js:1:278019)
    at _next (main.0.31.0-dev.1677054177163.js:1:278330)
```

**Comment by yann300** [comment]
should be fixed by https://github.com/ethereum/remix-project/pull/3418
please double check
