### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by lifetin** [ethereum/remix-project#3942]
```
D:\test\chain>remixd -h
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- C:\nodejs\node_global\node_modules\@remix-project\remixd\src\bin\remixd.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1003:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:107:18)[39m
    at Object.<anonymous> (C:\nodejs\node_global\node_modules\[4m@remix-project[24m\remixd\src\bin\remixd.js:4:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1114:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:979:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:819:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\nodejs\\node_global\\node_modules\\@remix-project\\remixd\\src\\bin\\remixd.js'[39m
  ]
}

```

Why is this situation happening?

**Comment by Aniket-Engg** [comment]
is it happening with other remix commands too?

**Comment by joeizang** [comment]
@lifetin I am using Windows 11 pro and I have node 20.5.0 installed and remixd installed globally. I cannot replicate the error you just posted. Can you give us more context on how you are getting this error?

**Comment by fwx5618177** [comment]
Could you try to these steps?

1. Remove node_modules.
2. Use "node": "^20.0.0"
3. Re-install by using `npm i`
4. Check your `node_modules`. For example, use `chmod -R 777 node_modules`
5. Re-run `remixd -h`. And hope you to paste or upload your screenshoots.

**Comment by Aniket-Engg** [comment]
@lifetin is it fixed for you?
