### ISSUE TITLE
Issue with contract deployed using ts file

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#4185]
- [ ] It shows this error in browser console on deploying a contract using ts file:

```
provider.ts:96 Uncaught (in promise) Error: unknown method eth_chainId
    at Provider._send (provider.ts:96:14)
    at provider.ts:110:12
    at new Promise (<anonymous>)
    at Provider.sendAsync (provider.ts:100:12)
    at self.onmessage (worker-vm.ts:27:16)
```

- [ ] On Method interaction, it shows this error in browser console

```
TypeError: Cannot read properties of undefined (reading 'getContracts')
    at _callee3$ (terminalAction.ts:139:77)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:20)
    at _next (asyncToGenerator.js:25:9)
```

- [ ] There is one small issue. When we deploy a contract, and expand the deployed instance in Udapp, it shows balance as `0 ETH` but after 3-5 seconds, it updates to `0. ETH`

**Comment by yann300** [comment]
> here is one small issue. When we deploy a contract, and expand the deployed instance in Udapp, it shows balance as 0 ETH but after 3-5 seconds, it updates to 0. ETH

this is an issue in the web3 lib, but I didn't yet raise the issue to them
