### ISSUE TITLE
Calling contract functions reloads the IDE

### ISSUE THREAD

**Issue by 0f0crypto** [ethereum/remix-project#4208]
Calling functions on deployed contracts (loaded in via ABI) reloads/crashes the IDE.

# Steps to reproduce

* Write a simple contract with a single address variable `owner`, compile it (here I'm using the 0.6.12 as the target contract was complied with that compiler version)

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.12;

contract Ownable {
    address private _owner;

    function owner() external view returns (address) {
        return _owner;
    }
}
```

* Compile the contract and load, for example, the [USDC](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readProxyContract) contract on main net @ 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

* Calling the `owner()` function briefly returns the result `0xFcb19e6a322b27c06842A71e8c725399f049AE3a` and then the IDE crashes. 

![image](https://github.com/ethereum/remix-project/assets/79452698/3d6dc3dd-64e4-49c6-8f1b-ec80f71a3b36)

The console shows the following errors:

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Context (162.0.37.0.1699376748839.js:1:2176997)
    at Ch (main.0.37.0.1699376748839.js:1:3354658)
    at ck (main.0.37.0.1699376748839.js:1:3402248)
    at bk (main.0.37.0.1699376748839.js:1:3394416)
    at ak (main.0.37.0.1699376748839.js:1:3394347)
    at Tj (main.0.37.0.1699376748839.js:1:3394206)
    at Lj (main.0.37.0.1699376748839.js:1:3391056)
    at main.0.37.0.1699376748839.js:1:3340310
    at exports.unstable_runWithPriority (main.0.37.0.1699376748839.js:1:3619133)
    at gg (main.0.37.0.1699376748839.js:1:3340087)
    
TypeError: Cannot set properties of null (setting 'currentContent')
    at ref (162.0.37.0.1699376748839.js:1:2614531)
    at Vi (main.0.37.0.1699376748839.js:1:3380967)
    at bj (main.0.37.0.1699376748839.js:1:3383683)
    at cj (main.0.37.0.1699376748839.js:1:3385506)
    at dk (main.0.37.0.1699376748839.js:1:3397322)
    at exports.unstable_runWithPriority (main.0.37.0.1699376748839.js:1:3619133)
    at gg (main.0.37.0.1699376748839.js:1:3340087)
    at Uj (main.0.37.0.1699376748839.js:1:3395283)
    at Lj (main.0.37.0.1699376748839.js:1:3391264)
    at main.0.37.0.1699376748839.js:1:3340310
    
Uncaught TypeError: Cannot set properties of null (setting 'currentContent')
    at ref (162.0.37.0.1699376748839.js:1:2614531)
    at Vi (main.0.37.0.1699376748839.js:1:3380967)
    at bj (main.0.37.0.1699376748839.js:1:3383683)
    at cj (main.0.37.0.1699376748839.js:1:3385506)
    at dk (main.0.37.0.1699376748839.js:1:3397322)
    at exports.unstable_runWithPriority (main.0.37.0.1699376748839.js:1:3619133)
    at gg (main.0.37.0.1699376748839.js:1:3340087)
    at Uj (main.0.37.0.1699376748839.js:1:3395283)
    at Lj (main.0.37.0.1699376748839.js:1:3391264)
    at main.0.37.0.1699376748839.js:1:3340310
    
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at Context (162.0.37.0.1699376748839.js:1:2176997)
    at Ch (main.0.37.0.1699376748839.js:1:3354658)
    at ck (main.0.37.0.1699376748839.js:1:3402248)
    at bk (main.0.37.0.1699376748839.js:1:3394416)
    at ak (main.0.37.0.1699376748839.js:1:3394347)
    at Tj (main.0.37.0.1699376748839.js:1:3394206)
    at Lj (main.0.37.0.1699376748839.js:1:3391056)
    at main.0.37.0.1699376748839.js:1:3340310
    at exports.unstable_runWithPriority (main.0.37.0.1699376748839.js:1:3619133)
    at gg (main.0.37.0.1699376748839.js:1:3340087)
```

Browsers:

Google Chrome: Version 119.0.6045.106 (Official Build) (64-bit)
Microsoft Edge: Version 119.0.2151.44 (Official build) (64-bit)

Demo Video:

[![Youtube video demo](https://img.youtube.com/vi/_Mye2QMqWpA/0.jpg)](https://www.youtube.com/watch?v=_Mye2QMqWpA)

**Comment by Emilijus436** [comment]
I also have this issue.

**Comment by 0f0crypto** [comment]
> @0f0crypto Could you please confirm you have the issue with the latest (0.37.1) version?

Yes, actually now 0.37.2 has the same issue

**Comment by 0f0crypto** [comment]
Sorry closed by accident
