### ISSUE TITLE
@remix-project/remix-simulator: Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by wighawag** [ethereum/remix-project#4294]
After working around issue: https://github.com/ethereum/remix-project/issues/4293 by adding tslib as dependencies

I get an other error wtih vite project:

in browser console:
```
eip1559Transaction.ts:29 Uncaught ReferenceError: Buffer is not defined
    at node_modules/.pnpm/@ethereumjs+tx@4.2.0/node_modules/@ethereumjs/tx/dist/eip1559Transaction.js (eip1559Transaction.ts:29:33)
    at __require2 (@remix-project_remix-simulator.js?v=385ebe4f:18:50)
    at node_modules/.pnpm/@ethereumjs+tx@4.2.0/node_modules/@ethereumjs/tx/dist/index.js (index.ts:1:1)
    at __require2 (@remix-project_remix-simulator.js?v=385ebe4f:18:50)
    at node_modules/.pnpm/@remix-project+remix-lib@0.5.43_typescript@5.3.2/node_modules/@remix-project/remix-lib/src/execution/txRunnerVM.js (txRunnerVM.ts:4:1)
    at __require2 (@remix-project_remix-simulator.js?v=385ebe4f:18:50)
    at node_modules/.pnpm/@remix-project+remix-lib@0.5.43_typescript@5.3.2/node_modules/@remix-project/remix-lib/src/index.js (index.ts:16:1)
    at __require2 (@remix-project_remix-simulator.js?v=385ebe4f:18:50)
    at node_modules/.pnpm/@remix-project+remix-simulator@0.2.36_typescript@5.3.2/node_modules/@remix-project/remix-simulator/src/methods/txProcess.js (txProcess.ts:1:1)
    at __require2 (@remix-project_remix-simulator.js?v=385ebe4f:18:50)
```

Reproduction repo (branch: `buffer-missing`): https://github.com/wighawag/ethereum-remix-provider/tree/buffer-missing

```
git checkout buffer-missing
pnpm i
pnpm dev
# then navigate to localhost:5173 and see error
```

**Comment by wighawag** [comment]
I can get arround the issue by adding vite plugin `vite-plugin-node-polyfills` but as per vite docs, ideally packages should not use node polyfills

For example instead of `Buffer` it should use Uint8Array

**Comment by Aniket-Engg** [comment]
We can have a look to it. Moreover, to use `remix-simulator` in browser, you need to do some configuration to handle Buffer and other related things.

**Comment by wighawag** [comment]
Yes, ideally remix-simulator would work without any config, using pure web js (so instead of Buffer, Uint8Array, etc...). but I guess it depends on the dependencies remix-simulator depends on ?
