### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by abhishekfredrick** [ethereum/remix-project#4727]
![Screenshot 2024-04-16 173024](https://github.com/ethereum/remix-project/assets/77562888/3000e3a2-3e2c-467b-b418-516961404570)

Error in console:
Uncaught TypeError: Cannot read properties of null (reading 'selectorList')
    at _setCompilerVersionFromPragma (6042.0.47.0.1712745482991.js:1:2174862)
    at compileAndRun (6042.0.47.0.1712745482991.js:1:2179997)
    at Object.Nb (main.0.47.0.1712745482991.js:1:3306129)

**Comment by abhishekfredrick** [comment]
Not sure whether the chrome extension is causing the issue or any problem with my system, it work on another system.

**Comment by GoudhamT** [comment]
I got same error, does anyone of your issue is solved?
