### ISSUE TITLE
Why is there an undeclared dependency on npip?

### ISSUE THREAD

**Issue by oberondelafay** [ethereum/remix-project#500]
Are you guys testing your build process?  
Trying to install remixd and encountering failure after failure.  Originally I followed the instructions about installing with npm -g and got some error about could not CWD after a git operation because permission denied.  So I went and tried every other install method I could figure.

Finally found instructions telling me to install it locally.
That's when I ran into this...
```
make: Leaving directory '/home/username/Projects/remixd/node_modules/websocket/build'
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> remixd@0.1.8-alpha.6 prepublish /home/username/Projects/remixd
> npm run install-python-deps


> remixd@0.1.8-alpha.6 install-python-deps /home/username/Projects/remixd
> npip install

No python_modules directory; installing pip locally if needed.
Traceback (most recent call last):
  File "/home/username/Projects/remixd/node_modules/nopy/src/get-pip.py", line 20061, in <module>
    main()
  File "/home/username/Projects/remixd/node_modules/nopy/src/get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/username/Projects/remixd/node_modules/nopy/src/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpy03_qop6/pip.zip/pip/__init__.py", line 26, in <module>
  File "/tmp/tmpy03_qop6/pip.zip/pip/utils/__init__.py", line 23, in <module>
  File "/tmp/tmpy03_qop6/pip.zip/pip/locations.py", line 9, in <module>
ImportError: cannot import name 'sysconfig'
Error: Exited with code 1.
    at ChildProcess.child.on.code (/home/username/Projects/remixd/node_modules/nopy/src/api.js:279:20)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remixd@0.1.8-alpha.6 install-python-deps: `npip install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remixd@0.1.8-alpha.6 install-python-deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remixd@0.1.8-alpha.6 prepublish: `npm run install-python-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remixd@0.1.8-alpha.6 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My first question is why are we relying on python of all things to be installed on a system intended for solidity development.  My second question is what is npip and how to do install it because it doesn't seem to be available from 
```
npm install -g npip
```

**Comment by Aniket-Engg** [comment]
Closing because of inactivity.
