### ISSUE TITLE
Lose connection (remixd exit) when try to access deleted file

### ISSUE THREAD

**Issue by bingtimren** [ethereum/remix-project#506]
When a file is deleted (by 'rm some_file') and remix try to access it, remixd exit with an error:

fs.js:995
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat '/home/bing/git/contract_test/migrations/3_ttt.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:995:11)
    at Object.realpathSync (fs.js:1676:21)
    at isRealPath (/usr/local/lib/node_modules/remixd/src/services/sharedFolder.js:92:21)
    at Object.set (/usr/local/lib/node_modules/remixd/src/services/sharedFolder.js:36:10)
    at Router.call (/usr/local/lib/node_modules/remixd/src/router.js:16:27)
    at websocket.start (/usr/local/lib/node_modules/remixd/src/router.js:8:12)
    at WebSocketConnection.connection.on (/usr/local/lib/node_modules/remixd/src/websocket.js:43:11)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)

**Comment by yann300** [comment]
closing as old issue and fixed.
