### ISSUE TITLE
Remixd isn't connecting 

### ISSUE THREAD

**Issue by Code0x2** [ethereum/remix-project#845]
When I go to remix.ethereum.org, and click connect to localhost, my command line window running remixd shows the following error:
```
Fri Feb 05 2021 17:14:28 GMT-0800 (Pacific Standard Time) Remixd is listening on 127.0.0.1:65520
[WARN] You may now only use IDE at http://remix.ethereum.org to connect to that instance
setup notifications for solidity
Error: Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
```
Didnt happen until the latest version

**Comment by ioedeveloper** [comment]
It is fixed. Do uninstall and install.
```
npm uninstall -g remixd
npm install -g @remix-project/remixd --force
```

**Comment by Code0x2** [comment]
Ah, didnt reinstall the new one. Thanks!

**Comment by nicos99** [comment]
I had the same issue until reinstalling *remixd* but with an other error (due to les access right to `C:\`)
```
setup notifications for C:\Users\XXXX\Documents\dev\remix_shared_folder
Error: Error: EPERM: operation not permitted, lstat 'C:\Config.Msi'
    at RemixdClient.resolveDirectory (C:\Users\XXXX\AppData\Roaming\npm\node_modules\remixd\lib\src\services\remixdClient.js:36:19)
    at Object.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\remixd\node_modules\@remixproject\plugin-ws\node_modules\@remixproject\plugin\lib\connector.js:67:56)
```
