### ISSUE TITLE
remixd seems not read folder properly in Windows

### ISSUE THREAD

**Issue by UgOrange** [ethereum/remix-project#927]
I use remixd 0.2.4-alpha.0，when i try to used remixd with this command
`remixd -s E:\contract\metacoin\ --remix-ide https://remix.ethereum.org`
when i try to connect remixd, it will put these error
```[WARN] You may now only use IDE at https://remix.ethereum.org to connect to that instance
[WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.
[WARN] Symbolic links are not forwarded to Remix IDE

Thu Feb 25 2021 19:09:42 GMT+0800 (中国标准时间) Remixd is listening on 127.0.0.1:65520
setup notifications for E:\contract\metacoin\
Error: Error: EPERM: operation not permitted, lstat 'E:\System Volume Information'
    at RemixdClient.resolveDirectory (C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\lib\src\services\remixdClient.js:36:19)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_@remixproject_plugin@0.3.8@@remixproject\plugin\lib\connector.js:67:56)
    at Generator.next (<anonymous>)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_tslib@2.0.1@tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_tslib@2.0.1@tslib\tslib.js:110:16)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_@remixproject_plugin@0.3.8@@remixproject\plugin\lib\connector.js:30:86
    at WebSocket.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_@remixproject_plugin-ws@0.3.8@@remixproject\plugin-ws\lib\ws.js:18:49)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\dell\AppData\Roaming\npm\node_modules\remixd\node_modules\_ws@7.4.3@ws\lib\websocket.js:825:20)
```
it seems that remixd lstat E:\System Volume Information,but the target folder is E:\contract\metacoin\ .
I also try use E:/contract/metacoin/,but error still appeard,plz help me!

**Comment by Aniket-Engg** [comment]
@UgOrange Do you still see the issue with latest version of remixd?
